# CodeRabbit Configuration
# Reference: https://docs.coderabbit.ai/guides/configure

language: en
early_access: false

chat:
  auto_reply: true

review:
  auto_review: true
  review_status: true
  review_comment_sort_order: newest
  high_level_summary: true
  auto_label_based_review: true

exclude:
  - node_modules/**
  - .next/**
  - dist/**
  - build/**
  - coverage/**
  - .scannerwork/**
  - "*.pyc"
  - __pycache__/**
  - .env.local
  - .env
  - package-lock.json
