# CodeRabbit Configuration for ABACO Financial Intelligence Platform
language: en-US
early_access: false
tone_instructions: "Be concise, professional, and focus on security and best practices"

reviews:
  profile: assertive
  request_changes_workflow: true
  high_level_summary: true
  high_level_summary_placeholder: "<!-- CodeRabbit AI Review Summary -->"
  poem: false
  review_status: true
  collapse_walkthrough: false
  path_filters:
    - "!**/*.lock"
    - "!**/node_modules/**"
    - "!**/.next/**"
    - "!**/dist/**"
    - "!**/coverage/**"
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords:
      - "WIP"
      - "DO NOT REVIEW"
    drafts: false
    base_branches:
      - main
      - develop
  tools:
    github-actions:
      enabled: true
    biome:
      enabled: true
    shellcheck:
      enabled: true
    ruff:
      enabled: true
    markdownlint:
      enabled: true
    eslint:
      enabled: true
    actionlint:
      enabled: true

chat:
  auto_reply: true

knowledge_base:
  learnings:
    scope: auto
  issues:
    scope: auto
  jira:
    project_keys: []
  linear:
    team_keys: []
