name: CodeRabbit Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_review_comment:
    types: [created, edited]

permissions:
  contents: read
  pull-requests: write

jobs:
  coderabbit:
    name: CodeRabbit AI Review
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run CodeRabbit
        uses: coderabbitai/action@v2
        with:
          config_file: .coderabbit.yaml
          debug: false
